name: CI Check

on:
  push:
    branches: [deploy]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Test
        run: echo "CI working successfully"
